apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1nu5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-avwa-tenant/rhtap-demo-app/hacbs-test-project-1nu5@sha256:29491dc411e80e9e4f10769dd74a9558b3c68934b7f87c62944e6d1704557db0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
