apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1nu5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1nu5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1nu5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1nu5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1nu5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-avwa-tenant/rhtap-demo-app/hacbs-test-project-1nu5@sha256:29491dc411e80e9e4f10769dd74a9558b3c68934b7f87c62944e6d1704557db0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
